name: shengguo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2  
  # Http请求库，支持拦截器、请求取消、Cookie管理、文件上传/下载、超时、自定义适配器等
  # https://pub.dev/packages/dio#-readme-tab-
 
  dio: ^3.0.10
  # 轮播图使用
  flutter_swiper: ^1.1.6
  # 屏幕适配
  flutter_screenutil: ^0.5.1
  # 包含NSUserDefaults（在iOS上）和SharedPreferences（在Android上），
  # 为简单数据提供持久存储。数据以异步方式持久保存到磁盘。
  # 这两个平台都不能保证在返回后写入将持久保存到磁盘，并且此插件不能用于存储关键数据。
  # https://pub.dev/packages/shared_preferences#-readme-tab-
  shared_preferences: ^0.5.12+4
  # 接入html富文本展示
  flutter_html: ^0.9.6
  # 微信登录使用
  fluwx: ^1.2.1
  # 阿里百川
  # nautilus: ^0.0.7
  # 网易七鱼客服对接
  flutter_qiyu: ^0.0.1


  url_launcher: ^5.0.1
  flutter_easyrefresh: ^1.2.7
  provide: ^1.0.2
  fluttertoast: ^3.0.1 
  fluro: ^1.4.0
  sqflite: ^1.1.0
  flutter_statusbarcolor: ^0.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/tabbar_icon_home_normal.png
    - assets/icon/tabbar_icon_home_selected.png
    - assets/icon/tabbar_icon_classification_normal.png
    - assets/icon/tabbar_icon_classification_selected.png
    - assets/icon/tabbar_icon_task_normal.png
    - assets/icon/tabbar_icon_task_selected.png
    - assets/icon/tabbar_icon_mine_normal.png
    - assets/icon/tabbar_icon_mine_selected.png
    - assets/icon/icon_jingdong.png
    - assets/icon/icon_pinduoduo.png
    - assets/icon/icon_taobao.png
    - assets/icon/icon_tmall.png
    - assets/icon/order1.png
    - assets/icon/order2.png
    - assets/icon/order3.png
    - assets/icon/order4.png
    - assets/icon/mymenu1.png
    - assets/icon/mymenu2.png
    - assets/icon/mymenu3.png
    - assets/icon/mymenu4.png
    - assets/icon/mymenu5.png
    - assets/icon/mymenu6.png
    - assets/icon/mymenu7.png
    - assets/icon/mymenu8.png
    - assets/icon/gouwuche.png
    - assets/icon/haowu.png
    - assets/icon/yaoqing.png
    - assets/icon/dian.png
    

    - images/mytopbg.png
    - images/mytaskbg.png
    - images/loginbg.png
    - images/freepurchasebg.png
    - images/coursetbandroid.png
    - images/coursetbios.png
    - images/coursejd.png
    - images/coursepdd.png
    
    

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/iconfont/iconfont.ttf
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
